version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/frontend

hooks:
  BeforeInstall:
    - location: scripts/deploy.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/resstart.sh
      timeout: 300
