version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/frontend
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/deploy.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/restart.sh
      timeout: 300
