version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/frontend-only

hooks:
  BeforeInstall:
    - location: scripts/deploy.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/pm2start.sh
      timeout: 300
