version: 0.2

phases:
  install:
    commands:
      - echo Updating packages...
      - sudo apt-get update -y
      - echo Installing Nginx...
      - sudo apt-get install nginx -y
  build:
    commands:
      - echo Building the application...
  post_build:
    commands:
      - echo Replacing the index.html file...
      - if [ -f ./index.html ]; then sudo cp ./index.html /home/ubuntu/frontend-only/public/; else echo "index.html not found"; exit 1; fi
      - echo Starting Nginx...
      - sudo systemctl start nginx
      - sudo systemctl enable nginx

artifacts:
  files:
    - '**/*'
