version: 0.2

phases:
  install:
    commands:
     
      - sudo yum install nginx -y
  build:
    commands:
      - echo Building the application...
  post_build:
    commands:
      - echo Replacing the index.html file...
      - sudo cp index.html  /var/www/html/
      - echo Starting Nginx...
      - sudo systemctl start nginx
      - sudo systemctl enable nginx

artifacts:
  files:
    - /var/www/html/index.html

