name: Build and Run React Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify the Node.js version you're using

    # Step 3: Install project dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Build the project
    - name: Build project
      run: npm run build

    # Step 5: Run tests (Optional, remove this step if not needed)
    - name: Run tests
      run: npm test

    # Step 6: Auto commit and push changes (if applicable)
    - name: Auto commit changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Auto commit changes after build"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

